# Generated by Django 2.0.2 on 2018-04-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eMenu', '0002_auto_20180424_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='menus',
            field=models.ManyToManyField(related_name='dishes', to='eMenu.Menu'),
        ),
    ]
