# Generated by Django 2.0.2 on 2018-04-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eMenu', '0003_auto_20180424_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
